### ISSUE TITLE
Running KBetweenness with k = 1 returns zero for all nodes.

### ISSUE THREAD

**Issue by xristosrou** [dmarcous/spark-beetweenness#2]
I just want to calculate the betweenness centrality for the nodes of a graph but i noticed that for different k's it returns different results , i assume that what i want is for k equal to 1 , i try to run the algorithm with k=1 but it returns zero for all nodes , i assumed that this was because the graph is directed so i added more edges , for example if there is an edge x -> y i added also the edge y -> x. I run the algorithm again and the result is still 0 for all nodes , the api is straightforward but i can not find the solution to my problem. I would appreciate it very much if you could help me.

Thanks.

**Comment by YotamSandbank** [comment]
Our algorithm computes the k-betweenness of a graph, which is not exactlly
the same as betweenness.
K-betweenness is betweenness calculated only with paths with length <= k,
so the higher k you choose, the closer it will be to the actual betweenness.
If you choose k=1, you only consider paths of length 1, which don't
contribute to any of the nodes' betweenness.
If you want to calculate the actual betweenness you'll have to do so with a
different package (if possible we recommend python's networkx),
but you should know that k-betweenness is a very good estimation of the
actual betweenness, and is usually sufficient for any betweenness-related
task you want to complete.

If you have anymore questions let us know,
Yotam and Daniel

2016-10-28 16:05 GMT+03:00 Xristos Roussakis notifications@github.com:

**Comment by xristosrou** [comment]
Thank you.
