### ISSUE TITLE
small diameter

### ISSUE THREAD

**Issue by geoHeil** [dmarcous/spark-beetweenness#3]
could you clarify what
> The method above ilustrated that spark-betweenness **works best for graphs with a small** diameter. We actually hold all k-graphlets in memory for Brandes calculation as they are the core of parallelizing this algorithm. Therefore, we manage to compute kBC on millions of nodes and vertices with large diameter graphs (such as road networks), but **fail miserabely to do so on small diameter** graphs (such as social networks).

means?
First you say a smal diameter is good, then the opposite.

**Comment by YotamSandbank** [comment]
Our bad,
We meant to say it works best with a *large* diameter.
Fixed,
Thanks!

2017-01-28 11:20 GMT+02:00 geoHeil <notifications@github.com>:
